use super::*;

impl Default for FontMetadata {
    fn default() -> Self {
        Self {
            family_name: "My Font".to_string(),
            style_name: "Regular".to_string(),
            copyright: String::new(),
            designer: String::new(),
            manufacturer: String::new(),
            vendor_id: default_vendor_id(),
            font_revision: 1.0,
            units_per_em: 1000.0,
            ascender: 800.0,
            descender: -200.0,
            line_gap: 0.0,
            italic_angle: 0.0,
            underline_position: -100.0,
            underline_thickness: 50.0,
            is_fixed_pitch: false,
            x_height: 0.0,
            cap_height: 0.0,
            weight_class: 400,
            width_class: 5,
            fs_type: 0,
            fs_selection: 0,
            head_flags: 0,
            head_mac_style: 0,
            lowest_rec_ppem: 0,
            font_direction_hint: default_font_direction_hint(),
            panose: default_panose(),
            default_char: 0,
            break_char: 0,
            max_context: 0,
            caret_slope_rise: 0,
            caret_slope_run: 0,
            caret_offset: 0,
            subscript_x_size: 0,
            subscript_y_size: 0,
            subscript_x_offset: 0,
            subscript_y_offset: 0,
            superscript_x_size: 0,
            superscript_y_size: 0,
            superscript_x_offset: 0,
            superscript_y_offset: 0,
            strikeout_size: 0,
            strikeout_position: 0,
            family_class: 0,
            lower_optical_point_size: 0,
            upper_optical_point_size: 0,
            vertical_caret_slope_rise: 0,
            vertical_caret_slope_run: 0,
            vertical_caret_offset: 0,
            win_ascent: 0,
            win_descent: 0,
        }
    }
}
