
/// Exports a static TTF generated by interpolating two master layers.
pub fn export_ttf_at_interpolation(
    project: &FontProject,
    from_master_id: &str,
    to_master_id: &str,
    factor: f64,
    path: &Path,
) -> Result<(), String> {
    if !factor.is_finite() {
        return Err("補間率が不正です".to_string());
    }
    let from = project
        .masters
        .iter()
        .find(|master| master.id == from_master_id)
        .cloned()
        .ok_or_else(|| format!("マスター '{}' がありません", from_master_id))?;
    let to = project
        .masters
        .iter()
        .find(|master| master.id == to_master_id)
        .cloned()
        .ok_or_else(|| format!("マスター '{}' がありません", to_master_id))?;
    let mut instance = project.clone();
    let t = factor.clamp(0.0, 1.0);
    let from_kerning = project
        .kerning_by_master
        .get(from_master_id)
        .unwrap_or(&project.kerning);
    let to_kerning = project
        .kerning_by_master
        .get(to_master_id)
        .unwrap_or(&project.kerning);
    let keys: std::collections::HashSet<_> = from_kerning
        .keys()
        .chain(to_kerning.keys())
        .cloned()
        .collect();
    instance.kerning = keys
        .into_iter()
        .filter_map(|key| {
            let a = from_kerning.get(&key).copied().unwrap_or(0.0);
            let b = to_kerning.get(&key).copied().unwrap_or(0.0);
            let value = a + (b - a) * t;
            (value.abs() > f64::EPSILON).then_some((key, value))
        })
        .collect();
    let instance_master_id = format!("instance-{t:.3}");
    for glyph in instance.glyphs.values_mut() {
        let from_layer = glyph.layers.get(from_master_id).cloned();
        let to_layer = glyph.layers.get(to_master_id).cloned();
        let (Some(a), Some(b)) = (from_layer, to_layer) else {
            if glyph.layers.is_empty() {
                continue;
            }
            return Err(if !glyph.layers.contains_key(from_master_id) {
                format!(
                    "グリフ '{}' に補間元マスター '{}' の層がありません",
                    glyph.name, from.name
                )
            } else {
                format!(
                    "グリフ '{}' に補間先マスター '{}' の層がありません",
                    glyph.name, to.name
                )
            });
        };
        let Some(layer) = a.interpolate(&b, t) else {
            return Err(format!(
                "グリフ '{}' のマスター形状を補間できません",
                glyph.name
            ));
        };
        glyph.width = layer.width;
        glyph.contours = layer.contours;
        glyph.components = layer.components;
        glyph.anchors = layer.anchors;
        glyph.layers.clear();
    }
    let mut interpolated_vertical = std::collections::HashMap::new();
    for name in project.glyphs.keys() {
        let a = project.vertical_metrics_for_glyph_in_master(name, from_master_id);
        let b = project.vertical_metrics_for_glyph_in_master(name, to_master_id);
        interpolated_vertical.insert(
            name.clone(),
            crate::font_data::VerticalMetrics {
                advance_height: a.advance_height + (b.advance_height - a.advance_height) * t,
                top_side_bearing: a.top_side_bearing
                    + (b.top_side_bearing - a.top_side_bearing) * t,
            },
        );
    }
    instance.vertical_metrics = interpolated_vertical;
    instance.vertical_metrics_by_master.clear();
    let mut master = from;
    master.id = instance_master_id;
    master.name = format!("{}–{} ({:.0}%)", master.name, to.name, t * 100.0);
    master.weight += (to.weight - master.weight) * t;
    master.width += (to.width - master.width) * t;
    let axis_tags: std::collections::HashSet<String> =
        master.axes.keys().chain(to.axes.keys()).cloned().collect();
    for tag in axis_tags {
        let a = master.axes.get(&tag).copied().unwrap_or(0.0);
        let b = to.axes.get(&tag).copied().unwrap_or(a);
        master.axes.insert(tag, a + (b - a) * t);
    }
    let mut axis_values = master.axes.clone();
    axis_values.insert("wght".into(), master.weight);
    axis_values.insert("wdth".into(), master.width);
    apply_conditional_layers(&mut instance, &axis_values);
    instance.masters = vec![master.clone()];
    instance.default_master_id = master.id;
    export_ttf(&instance, path)
}
