
/// Parse explicit GDEF ligature caret definitions. Feature File coordinates
/// are design-unit positions, while index definitions point to contour
/// positions; explicit records take precedence over the component-width
/// fallback generated by the editor.
fn parse_feature_ligature_carets(
    source: &str,
    glyph_ids: &std::collections::HashMap<&str, u16>,
) -> BTreeMap<GlyphId16, Vec<gdef::CaretValue>> {
    let mut carets = BTreeMap::new();
    for statement in source.split(';') {
        let tokens = statement.split_whitespace().collect::<Vec<_>>();
        let Some(kind_index) = tokens.iter().position(|token| {
            matches!(
                token.to_ascii_lowercase().as_str(),
                "ligaturecaretbypos" | "ligaturecaretbyindex"
            )
        }) else {
            continue;
        };
        let kind = tokens[kind_index].to_ascii_lowercase();
        let format = if kind == "ligaturecaretbypos" {
            1
        } else if kind == "ligaturecaretbyindex" {
            2
        } else {
            continue;
        };
        let Some(value_index) = tokens[kind_index + 1..]
            .iter()
            .position(|token| {
                token
                    .trim_matches(|character: char| "<>[],".contains(character))
                    .parse::<i32>()
                    .is_ok()
            })
            .map(|index| kind_index + 1 + index)
        else {
            continue;
        };
        let glyph_names = clean_feature_class(&tokens[kind_index + 1..value_index]);
        if glyph_names.is_empty() {
            continue;
        }
        let values = tokens[value_index..]
            .iter()
            .filter_map(|value| {
                value
                    .trim_matches(|character: char| "<>[],".contains(character))
                    .parse::<i32>()
                    .ok()
            })
            .filter_map(|value| {
                if format == 1 {
                    i16::try_from(value).ok()
                } else {
                    u16::try_from(value).ok().map(|value| value as i16)
                }
            })
            .map(|value| {
                if format == 1 {
                    gdef::CaretValue::format_1(value)
                } else {
                    gdef::CaretValue::format_2(value as u16)
                }
            })
            .collect::<Vec<_>>();
        if !values.is_empty() {
            for glyph_name in glyph_names {
                if let Some(&glyph_id) = glyph_ids.get(glyph_name.as_str()) {
                    carets.insert(GlyphId16::new(glyph_id), values.clone());
                }
            }
        }
    }
    carets
}
