use crate::font_data::{ColorGradient, FontMaster, FontProject, GlyphLayer};
use kurbo::{Arc, Point, SvgArc, Vec2};
use read_fonts::tables::gpos::{PairPos, PositionSubtables, SinglePos, ValueContext, ValueRecord};
use read_fonts::tables::gsub::{SingleSubst, SubstitutionSubtables};
use read_fonts::types::{GlyphId, NameId};
use read_fonts::{FontRef, Offset, TableProvider};
use std::io::Read;
use std::path::Path;
include!("../io_parts/part_000.rs");
include!("../io_parts/part_001.rs");
include!("../io_parts/part_002.rs");
include!("../io_parts/part_003.rs");
include!("../io_parts/part_004.rs");
include!("../io_parts/part_005.rs");
include!("../io_parts/part_006.rs");
include!("../io_parts/part_007.rs");
include!("../io_parts/part_008.rs");
include!("../io_parts/part_009.rs");
include!("../io_parts/part_010.rs");
include!("../io_parts/part_011.rs");
include!("../io_parts/part_012.rs");
include!("../io_parts/part_013.rs");
include!("../io_parts/part_014.rs");
include!("../io_parts/part_015.rs");
include!("../io_parts/part_016.rs");
include!("../io_parts/part_017.rs");
include!("../io_parts/part_018.rs");
include!("../io_parts/part_019.rs");
include!("../io_parts/part_020.rs");
include!("../io_parts/part_021.rs");
include!("../io_parts/part_022.rs");
include!("../io_parts/part_023.rs");
include!("../io_parts/part_024.rs");
include!("../io_parts/part_025.rs");
include!("../io_parts/part_026.rs");
include!("../io_parts/part_027.rs");
include!("../io_parts/part_028.rs");
include!("../io_parts/part_029.rs");
include!("../io_parts/part_030.rs");
include!("../io_parts/part_031.rs");
include!("../io_parts/part_032.rs");
include!("../io_parts/part_033.rs");
include!("../io_parts/part_034.rs");
include!("../io_parts/part_035.rs");
include!("../io_parts/part_036.rs");
include!("../io_parts/part_037.rs");
include!("../io_parts/part_038.rs");
include!("../io_parts/part_039.rs");
include!("../io_parts/part_040.rs");
include!("../io_parts/part_041.rs");
include!("../io_parts/import_ttf_variations.rs");
include!("../io_parts/part_042.rs");
include!("../io_parts/part_043.rs");
include!("../io_parts/part_044.rs");
include!("../io_parts/part_045.rs");
include!("../io_parts/part_046.rs");
include!("../io_parts/part_047.rs");
include!("../io_parts/part_048.rs");
